---
title: "Model performance and predictions for flow metrics"
author: ""
output: 
  html_document:
    css: kable.css
    includes: 
      in_header: cssloaders_in_header.html
self_contained: yes
runtime: shiny
---

```{r, message = F, warning = F, echo = F}
library(knitr)

opts_chunk$set(warning = FALSE, message = FALSE, dev.args = list(bg = 'transparent', family = 'serif'), eval = T, echo = F)
library(tidyverse)
library(shiny)
library(kableExtra)
library(lubridate)
library(kableExtra)
library(mapview)
library(leaflet)
library(sf)
library(shinycssloaders)

data(flowmetprf)

# complete performance table
dattaball <- flowmetprf %>% 
    select(-data, -impvars) %>% 
    gather('prf', 'val', rmse, rsqr) %>% 
    unite('prf', set, prf, sep = ' ') %>% 
    mutate(val = round(val, 2)) %>% 
    spread(prf, val) %>% 
    arrange(var, mo, modtyp)

# fold averaged performance table
dattabagg <- dattaball %>% 
  filter(modtyp %in% 'prdimp') %>% 
  gather('prf', 'val', `cal rmse`, `cal rsqr`, `val rmse`, `val rsqr`) %>% 
  group_by(var, mo, prf) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  spread(prf, val)

# fold and moth averaged performance table
dattabaggmo <- dattaball %>% 
  filter(modtyp %in% 'prdimp') %>% 
  gather('prf', 'val', `cal rmse`, `cal rsqr`, `val rmse`, `val rsqr`) %>% 
  group_by(var, mo, prf) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  group_by(var, prf) %>% 
  summarise(val = mean(val, na.rm = T)) %>% 
  spread(prf, val)
```

```{r selectors}
column(12, 
       column(3, 
              selectInput('metsel', 'Select metric:', choices = sort(unique(flowmetprf$var)))
              )
       )
```

```{r reactives}
# data to plot, table
datsel <- reactive({
  
  # inputs
  metsel <- input$metsel
  modsel <- input$modsel
  fldsel <- input$fldsel

  out <- flowmetprf %>% 
    filter(var %in% metsel) %>% 
    filter(modtyp %in% modsel) %>% 
    filter(fld %in% fldsel)
  
  return(out)
  
})

# table, selected
dattab <- reactive({
  
  # input
  datsel <- datsel()

  out <- datsel %>% 
    select(mo, set, rmse, rsqr) %>% 
    gather('var', 'val', rmse, rsqr) %>% 
    unite('var', set, var, sep = ' ') %>% 
    mutate(val = round(val, 2)) %>% 
    spread(var, val) %>% 
    arrange(mo) 
  
  return(out)
  
})

# imp predictors for the model
datimp <- reactive({
  
  # input
  datsel <- datsel()
  modsel <- input$modsel
  
  if(modsel == 'prd')
    out <- 'all'
  else 
    out <- datsel %>% 
      pull(impvars) %>%
      unlist %>% 
      unique %>% 
      sort %>% 
      paste(collapse = ', ')
  
  return(out)
    
})

# plot
output$datplo <- renderPlot({
  
  # input
  datsel <- datsel()
  
  toplo <- datsel %>% 
    select(mo, set, data) %>% 
    unnest
  
  p <- ggplot(toplo, aes(x = modprd, y = obs)) + 
    geom_point() + 
    facet_grid(set ~ mo) +
    geom_abline(intercept = 0, slope = 1) +
    geom_smooth(method = 'lm', se = F, linetype = 'dashed') + 
    theme_bw(base_family = 'serif', base_size = 16) + 
    xlab('Predicted') +
    ylab('Observed') + 
    theme(strip.background = element_blank())
  
  return(p)
  
}, height = 300)

```

# {.tabset}

## Model performance, selected metric

```{r}
column(12, 
       column(3, 
              selectInput('modsel', 'Select model type:', choices = list(full = 'prd', selected = 'prdimp'))
              ),
       
       column(3,
              selectInput('fldsel', 'Select fold:', choices = c(1:5))
              )
       )
```

```{r}
renderUI({
  HTML(knitr::kable(dattab(), caption = 'Summary statistics for selection.', format = 'html') %>% 
    kable_styling(full_width = T, font_size = 14))
})
```

Selected StreamCat predictors: `r renderText({datimp()})`

```{r}
plotOutput('datplo') %>% withSpinner()
```

## All performance

```{r}
renderDataTable(dattaball)
```

## Fold averaged performance

Results are for models based on top ten predictor variables.  

```{r}
renderDataTable(dattabagg)
```

## Fold and month averaged performance

Results are for models based on top ten predictor variables.  

```{r}
renderDataTable(dattabaggmo)
```